sea:
  ethercat:
    position_actual_value: "Position actual value" # 实际位置
    velocity_actual_value: "Velocity actual value" # 实际速度
    torque_actual_value: "Torque actual value" # 实际扭矩
    status_word: "Statusword" # 状态字
    secondary_position_value: "Secondary position value" # 辅助位置值
    secondary_velocity_value: "Secondary velocity value" # 辅助速度值
    mode_of_operation: "Mode of operation" # 操作模式
    control_word: "Controlword" # 控制字
    target_torque: "Target Torque" # 目标扭矩
    target_position: "Target Position" # 目标位置
    target_velocity: "Target Velocity" # 目标速度
  hardware:
    high_encoder_ppr: 262144 # 高速端分辨率 18bit
    low_encoder_ppr: 65536   # 低速端分辨率 14bit
    ratio: 100               #减速比100:1
    spring_stiffness: 126.0507 # 扭簧刚度 2.2Nm/° = 126.0507 Nm/rad
  impedance:
    stiffness: 7.0 # 弹簧刚度
    damping: 0.5   # 阻尼系数

